[package]
name = "shi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "4.0.0"
miniserde = "0.1.27"
sqlite = "0.27.0"
tabled = "0.9.0"
