[package]
name = "shi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1.6"
dirs = "4.0.0"
miniserde = "0.1.27"
serde = { version = "1.0.145", features = ["derive"] }
sqlite = "0.27.0"
tabled = "0.9.0"
